#pragma once
#include <stdint.h>
#include <cstddef>

namespace intel_driver_resource
{
	// Vulnerable Intel NAL diagnostic driver (iqvw64e.sys).
	//
	// This file is GENERATED by bat\embed_intel.bat from bin\iqvw64e.sys.
	// Do not edit by hand -- your changes will be overwritten on the next
	// embed run.
	//
	// The Mapper also checks for a copy of iqvw64e.sys next to the exe as
	// a runtime fallback (useful during development).
	inline const uint8_t driver_bytes[1] = { 0x00 };
	inline const size_t driver_bytes_size = 0; // 0 = placeholder (not yet embedded)
}
